apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.kompose.service: wtest
  name: wtest
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
status:
  loadBalancer: {}
